version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    # TODO must download jdbc on a temporary container
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./scripts:/usr/share/logstash/scripts
      - ./lib/postgresql-42.1.1.jar:/usr/share/logstash/lib/postgresql-42.1.1.jar
      - ./templates:/usr/share/logstash/templates
    depends_on: ['elasticsearch']
    command: bash -c "/usr/share/logstash/bin/logstash-plugin install logstash-filter-mutate && /usr/share/logstash/bin/logstash-plugin install logstash-input-jdbc && docker-entrypoint -e"

